import * as Addon from '../../Addon/Addon.styles';
import * as Bage from '../../Bage/Bage.styles';
import * as Divider from '../../Divider/Divider.styles';
import * as Paper from '../../Paper/Paper.styles';
import * as Svg from '../../Svg/Svg.styles';
import * as Text from '../../Text/Text.styles';
declare const _default: {
    color: {
        primary: string;
        primary1: string;
        primary2: string;
        secondary: string;
        secondary1: string;
        text: string;
        divider: string;
        paper: string;
        paper1: string;
        paper2: string;
        paper3: string;
        success: string;
        warning: string;
        color1: string;
        color2: string;
        color3: string;
        color4: string;
        color5: string;
        color6: string;
        color7: string;
        color8: string;
        color9: string;
        color10: string;
        color11: string;
        color12: string;
        color13: string;
        color14: string;
        color15: string;
        color16: string;
    };
    Addon: typeof Addon;
    Bage: typeof Bage;
    Divider: typeof Divider;
    Svg: typeof Svg;
    Paper: typeof Paper;
    Text: typeof Text;
};
export default _default;
